# This is a basic workflow to help you get started with Actions

name: Create Archive and Hash

# Controls when the workflow will run
on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
      run: git checkout HEAD^
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git*'
    - name: Put hash inside text file
      run: |
        touch "$(shasum -a 256 release.zip | grep -o '^[0-9a-z]*').hash"
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip, *.hash"
        token: ${{ secrets.GITHUB_TOKEN }}
