name: Resourcepack Zipper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # A non-shallow repository clone is required
    - name: Make Pack
      uses: ComunidadAylas/PackSquash-action@v4
      with:
        packsquash_version: latest
        options: |
          pack_directory = '.'
          output_file_path = '/tmp/release.zip'
    - name: Get Pack Hash
      run: |
        HASH=$(sha1sum /tmp/release.zip | grep -o "^[0-9a-z]*")
    - name: Tag and create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{github.run_number}}-${{ env.HASH }}
        files: /tmp/release.zip
